# Generated by Django 4.2.7 on 2023-11-13 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
