# Generated by Django 4.2.7 on 2023-11-14 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('level', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='head_image',
            field=models.ImageField(blank=True, upload_to='level/images/%Y/%m/%d/'),
        ),
    ]
